name: Publish to PyPi

on:
  # Publish to TestPyPI on every push to main
  push:
    branches: [main]

  # Publish to PyPI on version tags
  push:
    tags:
      - 'v*'

  # Publish to PyPI on GitHub releases
  release:
    types: [published]

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment target'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build package
      run: |
        pip install build
        python -m build

    - name: Publish to TestPyPI
      if: |
        github.event_name == 'push' && github.ref == 'refs/heads/main' ||
        github.event_name == 'workflow_dispatch' && inputs.target == 'testpypi'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      if: |
        github.event_name == 'release' ||
        startsWith(github.ref, 'refs/tags/v') ||
        github.event_name == 'workflow_dispatch' && inputs.target == 'pypi'
      uses: pypa/gh-action-pypi-publish@release/v1
